### ISSUE TITLE
Updating FAQ page with new conda info

### ISSUE THREAD

**Issue by hCraker** [NCAR/esds#221]
The majority of questions I get during ESDS office hours are related to using conda and more specifically using conda with NCAR HPC systems. Information and tutorials are out there, but they are hard to find. I think it would be helpful to users if we create a standing page on the website with a summary of the basics and a list of links.

Things to consider including:
- [conda cheat sheet](https://docs.conda.io/projects/conda/en/latest/_downloads/843d9e0198f2a193a3484886fa28163c/conda-cheatsheet.pdf) This link always points to the latest version of the sheet.
- [Using conda envs for Python access](https://arc.ucar.edu/knowledge_base/83853599) An NCAR specific page with instructions on how to clone, make, and use conda envs on the HPC systems
- quick summary of what the NPL conda environment contains
- general trouble shooting tips
    - are you using your own miniconda install or the recommended NCAR provided one through `module load conda/latest`?
    - `conda update conda`
    - `conda update --name my_env --all`
    - check if you have any pinned versions of packages. Remove pins that you no longer need
- links to the [NCAR Research Computing Helpdesk](https://ithelp.ucar.edu/plugins/servlet/desk/site/rc)

If anyone has suggestions for this page, please comment them! Thanks.

**Comment by erogluorhan** [comment]
This page could even have a FAQ, which could be populated through the questions you are receiving and are common enough or can be generalized by you.

**Comment by hCraker** [comment]
Great idea! I'll make this a more general faq page

**Comment by hCraker** [comment]
So we already have a general FAQ page, and my original intent with this issue was to create a separated page for conda help and basic troubleshooting. Instead, I'm going to update the current conda FAQ section and add some more resources because it has outdated information (e.g it's no longer recommended to have your own miniconda install in your work directory)

**Comment by erogluorhan** [comment]
That sounds great!

**Comment by erogluorhan** [comment]
Further thought here: Even though there is benefit in providing FAQ and conda support pages, I think the most efficient way forward is to cooperate with NCAR's consulting group (cc'ing Brian @vanderwb) so that we can avoid duplicating efforts, as well as we can link readers to the documentation they are providing instead of putting things together by ourselves.

**Comment by hCraker** [comment]
That's what I'm doing so far. I'm adding a very short summary of what's on the HPC pages and then linking to those sites. The only new information I plan on adding that isn't elsewhere on NCAR webpages is the conda cheet sheet and information on how to export and share environments.
