### ISSUE TITLE
seasonal averages dimension comment

### ISSUE THREAD

**Issue by zmoon** [NCAR/esds#223]
https://ncar.github.io/esds/posts/2022/xarray-groupby-vs-geocat-climatology/#the-incorrect-way-to-compute-seasonal-averages-from-monthly-data

> ... Notice that the result has a `month` dimension. ...

The result appears to have the correct `season` dimension, no `month` dimension.

**Comment by hCraker** [comment]
Whoops that is my mistake. I will fix this typo shortly
