### ISSUE TITLE
Add meeting notes section to the website

### ISSUE THREAD

**Issue by mgrover1** [NCAR/esds#61]
Based on conversation with @andersy005 , it would be good to add a work-in-progress notes section to the site

**Comment by andersy005** [comment]
We might be able to take full advantage of the "Publish" feature of Google Docs


![Screen Shot 2021-06-07 at 3 21 44 PM](https://user-images.githubusercontent.com/13301940/121089255-1e30a300-c7a4-11eb-8d5f-599122c12ec5.png)
![Screen Shot 2021-06-07 at 3 21 31 PM](https://user-images.githubusercontent.com/13301940/121089260-1f61d000-c7a4-11eb-9454-e5e49eb1241e.png)
