### ISSUE TITLE
Add an Active Projects page

### ISSUE THREAD

**Issue by mgrover1** [NCAR/esds#78]
An action item for the GeoCAT-Xdev meeting was to create an active projects page on the ESDS site.

Some projects to include would be:
* GeoCAT
     * comp
     * viz
* Diagnostics efforts?
* ESDS page?

**Comment by kmpaul** [comment]
- Include the Diagnostics efforts if there is a page (i.e., link) to them and/or if they are official projects with someone behind them.
- What do you mean by the "ESDS page"?
- Include the Xdev efforts like intake-esm and jupyter-forward, too.  Maybe there are others?  @NCAR/xdev

**Comment by mgrover1** [comment]
> * Include the Diagnostics efforts if there is a page (i.e., link) to them and/or if they are official projects with someone behind them.
> * What do you mean by the "ESDS page"?
> * Include the Xdev efforts like intake-esm and jupyter-forward, too.  Maybe there are others?  @NCAR/xdev

Sounds good - by the ESDS page, I meant this repo? But we can leave that out.
