### ISSUE TITLE
Separate Xdev site from ESDS

### ISSUE THREAD

**Issue by kmpaul** [NCAR/esds#95]
There is a *lot* of content in the Xdev repository that has been lost due to the automatic forward of the Xdev GitHub page to the ESDS GitHub page.  That is problematic, especially since (in our recent Xdev Team Meetings) the Xdev Team has (themselves) claimed that they are *not only* members of ESDS.  In other words, we have all agreed that (sometimes) Xdev and ESDS are different.  (Or, another way of saying it is that Xdev isn't an element inside ESDS, but a separate entity that has substantial overlap with ESDS.)  Hence, it makes sense that the two pages should be separate. 

I think we should separate the two pages.  And I think we should move the Xdev blog posts to the ESDS repo.  The rest of the content in the Xdev page is still useful on its own (and I need to work on updating it...but I want the GitHub page working.)

**Comment by kmpaul** [comment]
Done.  Now we just need to manually move the Xdev blog contents to ESDS and update the Xdev site to disable the blog.

**Comment by andersy005** [comment]
New Xdev site: https://github.com/ncar-xdev/ncar-xdev.github.io
